" Show invisible characters
set tabstop=2

set list
set listchars=tab:>-,trail:·,nbsp:·,extends:>,precedes:<

set number

IndentGuidesEnable

let g:ycm_clangd_binary_path = trim(system('brew --prefix llvm')).'/bin/clangd'
let g:ctrlp_tabpage_position = 'ac'

call plug#begin('~/.vim_runtime/my_plugins')
Plug 'christoomey/vim-tmux-navigator'
call plug#end()
