apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: namespace
resources:
- namespace.yaml

transformers:
- common-labels.yaml

patches:
- path: deployment.yaml

configMapGenerator:
- name: env-vars
  literals:
  - API_LOG_LEVEL=ERROR
  - SERVICES_LOG_LEVEL=ERROR

images:
- name: nginx
  newName: private/nginx:1.2.3
