apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-unique-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-role
subjects:
- kind: ServiceAccount
  name: my-sa
  namespace: my-ns
