# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

## ZSH defaults
export TERRAFORM_VERSION=0.12.13
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export ZSH=${HOME}/.oh-my-zsh
export ZSH_TMUX_AUTOCONNECT=true
ZSH_THEME=powerlevel10k/powerlevel10k
plugins=(terraform docker docker-compose zsh-syntax-highlighting zsh-autosuggestions git tmux virtualenv kubectl aws globalias)
source $ZSH/oh-my-zsh.sh

# Theme settings
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs kubectx)

source ${HOME}/.siebjee_tooling
source ${TOOLING_BASE_DIR}/zsh/environment.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
